DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS citext;
DROP EXTENSION IF EXISTS pgcrypto;
DROP EXTENSION IF EXISTS "uuid-ossp";
